### PR TITLE
Added "GitHub Dark Default" theme

### PR DESCRIPTION
**Pull request by SpiritAxolotl**
Extension with this theme: https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme

I've also published all the relevant original css colors in [this gist](https://gist.github.com/SpiritAxolotl/1f0f8f305fb7f6adf28596fbf145ef47).

It's worth noting that function parameters aren't orange. Compare these two images.

Codehost:  
codehost

VSCode:  
vscode

I couldn't figure out how to add them, or if they're even supported. Oh well.  
It's also worth noting that the colored bracket pairs don't exist, but that's probably not a priority lol.

### CODE REVIEW

**Comment by wavebeem** [comment]
yeahhhh, vscode themes have a lot more "detail" possible due to having more named tokens than prism supports.

thanks for the new theme!

my only question is what's up with the package-lock.json change? it seems like a lot of packages were upgraded or something?

image

also, would these themes normally have a status bar color that's different? the other themes have been customized along the bottom with a little "footer" style

image

**Comment by SpiritAxolotl** [comment]
> my only question is what's up with the package-lock.json change? it seems like a lot of packages were upgraded or something?

npm warned me of a few security vulnerabilities so I ran `npm audit fix`.
Screenshot 2024-05-06 at 10 54 39 PM
Feel free to revert that change if you want.

As for the second background color, I didn't realize it styled that aspect of it so let me fix that real quick haha.

I might help with contribution documentation at a later date if you're okay with that

**Comment by wavebeem** [comment]
> I might help with contribution documentation at a later date if you're okay with that

yeah im up for further contribution!

feel free to use [github discussions](https://github.com/wavebeem/codehost/discussions) or issues as appropriate

you can message me on discord if it's more involved and you want to talk at length about it

* * *

is the theme ok to merge? i noticed your MR is marked as draft, but it looks ready to go to me!

**Comment by SpiritAxolotl** [comment]
yeah I marked it as a draft because I didn't know if the theme was "complete". seems it is, since you mentioned that vscode themes has more named tokens than prism.

as for the documentation, I'm supposed to be on break from social media right now ~~(help github has become my new social media)~~ so I can discuss when I'm not so busy with my schoolwork!

**Comment by SpiritAxolotl** [comment]
oh yeah you might wanna update the changelog

**Comment by wavebeem** [comment]
oops, thanks for the reminder. just added it and credited u

**Pull request merged**
